# .github/gitleaks.toml

title = "GitLeaks Configuration"

[extend]
useDefault = true    # Use the default config as a base

# Custom rules
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey|secret)[_-]?[[:alnum:]]{16,}'''
secretGroup = 1
entropy = 3.5

# Allowlist specific files or patterns
[[rules.allowlists]]
description = "Ignored files and commits"
condition = "OR"
paths = [
    '''netbox-docker/docker/docker-entrypoint.sh''',
    '''(?i)test[/_-]files''',
    '''(?i)\.example$'''
]
# Allowlist specific commits (e.g., false positives)
#commits = [
    # "your-commit-hash-here"
#]
