---
extends: "default"
# Rules HERE ->  https://yamllint.readthedocs.io/en/stable/rules.html#
rules:
  brackets:
    max-spaces-inside: 2
  comments: "enable"
  empty-values: "disable"
  indentation:
    indent-sequences: "consistent"
  line-length: "disable"
  quoted-strings:
    quote-type: "double"
ignore: |
  .venv/
  docs/
